### PR TITLE
Back-port AssuranceCertificationMatcher from upstream MDA 0.10

### PR DESCRIPTION
**Pull request by philsmart**
- Change Java Predicates to Guava Predicates
 - Add MockContextImpl to test class

### CODE REVIEW

**Comment by philsmart** [comment]
That all makes sense. Thank you for the info. I will update the PR with those changes.

**Comment by philsmart** [comment]
I added to the release notes and included a template parent bean in beans.xml

**Comment by philsmart** [comment]
Sorry, I made a mistake in the `ukf.AssuranceCertificationMatcher` abstract parent bean. I made it a child of the `ukf.stage_parent` bean, which of course it is not, it is a predicate, and will fail as it does not have an init method. 

I will create a new PR to fix it.

**Comment by iay** [comment]
No problem. This is the point of the sort of integration testing we discussed on Friday.

**Comment by philsmart** [comment]
Thanks. Yes, the integration testing caught it.

**Pull request merged**
